version: "3.7"

services:
  app:
    container_name: d-system_web
    build:
      context: .
      dockerfile: apache/Dockerfile/Dockerfile
    volumes:
      - ../d-system-web:/var/www/html
      - ./apache/logs:/var/www/html/app/tmp/logs
    ports:
      - 8080:80
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - db

  db:
    container_name: d-system_mariadb
    build:
      context: .
      dockerfile: mariadb/Dockerfile/Dockerfile
    volumes:
      - ./mariadb/db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=d-system
      - MYSQL_DATABASE=d-system
      - "TZ=Asia/Tokyo"

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db
